# GitHub Pages Configuration

# Configuración para Jekyll (GitHub Pages)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración del sitio
title: "Papiweb - Desarrollos Informáticos"
description: "Soluciones de desarrollo informático, diseño web, aplicaciones móviles y software a medida"
url: "https://papiweb-desarrollos.github.io"
baseurl: "/papiweb"

# Configuración de archivos
include:
  - _pages
  - public
  - branding.html
  - papiweb_branding.html
  - robots.txt
  - sitemap.xml
  - media.json
  - manifest.json
  - favicons

# Excluir archivos de desarrollo
exclude:
  - test_*.html
  - debug_*.html
  - DIAGNOSTICO_*.md
  - REPORTE_*.md
  - FAVICON_*.md
  - README.md
  - server.js
  - package.json
  - node_modules
  - .vscode

# Configuración de marca
author: "Papiweb"
logo: "/favicons/favicon-192x192.png"

# Redes sociales
social:
  name: "Papiweb"
  links:
    - "https://github.com/papiweb"

# SEO
lang: "es"
timezone: "America/Argentina/Buenos_Aires"

# Configuración adicional
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# GitHub Pages configuración
repository: "papiweb-desarrollos/papiweb"
github:
  repository_url: "https://github.com/papiweb-desarrollos/papiweb"
